apiVersion: v1
kind: Pod
metadata:
  name: pod2containers
  labels: 
    app: POD-2-Containers
spec:
  containers:
  - name: some-watcher
    image: afakharany/watcher
  - name: some-nginx
    image: nginx
    ports:
    - name: nginx_port
      containerPort: 80
